import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  // Manual definition removes the autogenerated "Overview" and "Documentation" labels
  tutorialSidebar: [
    {
      type: 'doc',
      id: 'index', // Points to your docs/index.md
      label: 'Executive Summary',
    },
  ],
};

export default sidebars;
